# Generated by Django 3.0 on 2022-09-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time_arrive", models.DateTimeField(null=True)),
                ("date_time_delivery", models.DateTimeField(null=True)),
                ("latitude_arrrive", models.FloatField(default=0)),
                ("length_arrrive", models.FloatField(default=0)),
                ("latitude_delivery", models.FloatField(default=0)),
                ("length_delivery", models.FloatField(default=0)),
            ],
        ),
    ]
